// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvzwoWeeiWNXwSQJcxk1MJBY5tdm180N0',
    appId: '1:471002622225:web:203c473c74fe03280644b0',
    messagingSenderId: '471002622225',
    projectId: 'fullstack-auth-b579f',
    authDomain: 'fullstack-auth-b579f.firebaseapp.com',
    storageBucket: 'fullstack-auth-b579f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDis7OKCfIQHOBgf4PbjMO7eMQ5GmT_bm0',
    appId: '1:471002622225:android:1b6af16c453f31fd0644b0',
    messagingSenderId: '471002622225',
    projectId: 'fullstack-auth-b579f',
    storageBucket: 'fullstack-auth-b579f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASUNbrynhfA0R611QSseQqXEG3PPtfYtM',
    appId: '1:471002622225:ios:593aa496ae4bdec20644b0',
    messagingSenderId: '471002622225',
    projectId: 'fullstack-auth-b579f',
    storageBucket: 'fullstack-auth-b579f.appspot.com',
    iosBundleId: 'com.example.fullstackApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASUNbrynhfA0R611QSseQqXEG3PPtfYtM',
    appId: '1:471002622225:ios:ddc8e0d9913ff7990644b0',
    messagingSenderId: '471002622225',
    projectId: 'fullstack-auth-b579f',
    storageBucket: 'fullstack-auth-b579f.appspot.com',
    iosBundleId: 'com.example.fullstackApp.RunnerTests',
  );
}
